sudo: required

services:
  - docker

env:
  global:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=drupal
    - MYSQL_DATABASE=drupal
    - MY_NETWORKS=10.0.0.0/8 172.0.0.0/8 192.168.0.0/16 127.0.0.0/8
    - ROOT_ALIAS=robert@meinit.nl
    - MAILNAME=drupal.meinit.nl
    - DBURL=mysql://drupal:drupal@mysql/drupal
    - DBHOST=mysql
    - SITENAME=drupal
    - ADMINPASS=newpass

install:
- docker build . -t robertdebock/docker-drupal

script:
- docker-compose up --detach
- echo "Waiting 45 seconds for Drupal to become availale."
- timer=45 ; while [ ${timer} -gt 0 ] ; do sleep 6 ; timer=$[${timer}-6] ; echo "${timer}" ; done
- bats tests/

notifications:
  email: false
