sudo: required

services:
  - docker

env:
  global:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=drupal
    - MYSQL_DATABASE=drupal
    - MY_NETWORKS=10.0.0.0/8 172.0.0.0/8 192.168.0.0/16 127.0.0.0/8
    - ROOT_ALIAS=robert@meinit.nl
    - MAILNAME=drupal.meinit.nl


install:
- docker build . -t robertdebock/docker-drupal
- docker run -d mysql \
  --env MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD} \
  --env MYSQL_USER=${MYSQL_USER} \
  --env MYSQL_PASSWORD=${MYSQL_PASSWORD} \
  --env MYSQL_DATABASE=${MYSQL_DATABASE}
- docker run -d tozd/postfix \
  --env MY_NETWORKS=${MY_NETWORKS} \
  --env ROOT_ALIAS=${ROOT_ALIAS} \
  --env MAILNAME=${MAILNAME}
- docker run -p 80:80 \
  --link=mysql \
  --link=postfix \
  robertdebock/docker-drupal

script:
- docker run -p 80:80 robertdebock/docker-drupal
- wget http://localhost/drupal
- docker kill -l

notifications:
  email: false
