sudo: required

services:
  - docker

env:
  global:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=drupal
    - MYSQL_DATABASE=drupal
    - MY_NETWORKS=10.0.0.0/8 172.0.0.0/8 192.168.0.0/16 127.0.0.0/8
    - ROOT_ALIAS=robert@meinit.nl
    - MAILNAME=drupal.meinit.nl
    - DBURL=mysql://drupal:drupal@mysql/drupal
    - DBHOST=mysql
    - SITENAME=drupal
    - ADMINPASS=newpass

install:
- docker build . -t robertdebock/docker-drupal

script:
- docker run --name mysql --detach --env MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD} --env MYSQL_USER=${MYSQL_USER} --env MYSQL_PASSWORD=${MYSQL_PASSWORD} --env MYSQL_DATABASE=${MYSQL_DATABASE} mysql
- docker run --name postfix --detach --env MY_NETWORKS=${MY_NETWORKS} --env ROOT_ALIAS=${ROOT_ALIAS} --env MAILNAME=${MAILNAME} tozd/postfix
- docker run --name drupal --detach --publish 80:80 --link=mysql --link=postfix --env DBURL=${DBURL} --env DBHOST=${DBHOST} --env SITENAME=${SITENAME} --env ADMINPASS=${ADMINPASS} robertdebock/docker-drupal
- echo "Waiting 45 seconds for Drupal to become availale."
- timer=45 ; while [ ${timer} -gt 0 ] ; do sleep 6 ; timer=$[${timer}-6] ; echo "${timer}" ; done
- bats tests/
- curl http://localhost/drupal/user/login --cookie-jar cookies.txt -F 'name=admin' -F 'pass=newpass' -F 'form_id=user_login_form' -F 'op=Log+in'
- curl http://localhost/drupal/admin/reports/status --cookie cookies.txt

notifications:
  email: false
