sudo: required

services:
  - docker

env:
  global:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=drupal
    - MYSQL_DATABASE=drupal
    - MY_NETWORKS=10.0.0.0/8 172.0.0.0/8 192.168.0.0/16 127.0.0.0/8
    - ROOT_ALIAS=robert@meinit.nl
    - MAILNAME=drupal.meinit.nl
    - DBURL=mysql://drupal:drupal@mysql/drupal
    - DBHOST=mysql
    - SITENAME=drupal
    - ADMINPASS=newpass

install:
  - docker build . -t robertdebock/docker-drupal

script:
  - docker-compose up -d
  - echo "Waiting for Drupal to become availale."
  - until $(curl --output /dev/null --silent --head --fail http://localhost/drupal/) ; do echo -n "." ; sleep 1 ; done
  - bats tests/

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=robertdebock/docker-drupal
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

notifications:
  email: false
