version: '2'
services:
  drupal:
    image: drupal
    ports:
      - 80:80
      - 443:443
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
